### ISSUE TITLE
How to use Cloud Code with this image

### ISSUE THREAD

**Issue by mnlbox** [bitnami/bitnami-docker-parse-dashboard#29] opened 2018-07-25 12:25 UTC
Hi, I want to use [Cloud Code](https://docs.parseplatform.org/cloudcode/guide/#getting-started) with this images please guide me to do this. I Also try to create `cloud` directory in parse mounted directory and add some code to that but after doing this my server can't start and all of things totally.

Thanks for your attention.

**/CC:** @javsalgar

**Comment by andresbono** [comment] 2018-07-27 07:57
Hi @mnlbox!

What is the exact error message that you are getting?

Note that for information regarding the application itself or customization of the content within the application, we highly recommend checking forums and user guides made available by the project behind the application. Please check https://stackoverflow.com/tags/parse.com.

**Comment by mnlbox** [comment] 2018-07-30 07:02
This is my `folder structure`:
```
- run with current user
- parse_data
- - parse
- - - .initialized
- - - .restored
- - - cloud
- - - - main.js
- - - config.json
- mongodb_data
- - mongodb
- - - data
- - - - db
- - - - - index-6--6485419934143298406.wt
- - - - - index-1-3578409740711450837.wt
- - - - - index-9-3578409740711450837.wt
- - - - - collection-5-3578409740711450837.wt
- - - - - collection-4--6485419934143298406.wt
- - - .initialized
- - - .restored
- cloud
- - main.js <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< THIS IS MY CLOUD CODE
- parse_dashboard_data
- - parse-dashboard
- - - .initialized
- - - .restored
- - - config.json
- docker-compose.yml

```
This is my `docker-compose.yml`:
```
version: '2'
services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - '8080:27017'
    # user: ${CURRENT_UID}
    volumes:
      - './mongodb_data:/bitnami'
  parse:
    image: 'bitnami/parse:latest'
    ports:
      - '1337:1337'
    volumes:
      - './parse_data:/bitnami'
    depends_on:
      - mongodb
  parse-dashboard:
    image: 'bitnami/parse-dashboard:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:4040'
    volumes:
      - './parse_dashboard_data:/bitnami'
    depends_on:
      - parse
volumes:
  mongodb_data:
    driver: local
  parse_data:
    driver: local
  parse_dashboard_data:
    driver: local
```
This is my `/parse_data/parse/config.json` content:
```
{
  "appId": "myappID",
  "masterKey": "mymasterKey",
  "readOnlyMasterKey": "123456",
  "clientKey": "123",
  "restAPIKey": "123",
  "javascriptKey": "123",
  "appName": "parse-server",
  "mountPath": "/parse",
  "port": "1337",
  "host": "0.0.0.0",
  "serverURL": "http://127.0.0.1:1337/parse",
  "databaseURI": "mongodb://bn_parse:efJIk3I0ow@mongodb:27017/bitnami_parse"
}
```

This is my `main.js` file content:
```
Parse.Cloud.define("averageStars", function(request, response) {
  const query = new Parse.Query("Review");
  query.equalTo("movie", request.params.movie);
  query.find()
    .then((results) => {
      let sum = 0;
      for (let i = 0; i < results.length; ++i) {
        sum += results[i].get("stars");
      }
      response.success(sum / results.length);
    })
    .catch(() =>  {
      response.error("movie lookup failed");
    });
});
```
This is my `curl` request call:
```
curl -X POST \
  -H "X-Parse-Application-Id: myappID" \
  -H "X-Parse-REST-API-Key: 123" \
  -H "Content-Type: application/json" \
  -d '{ "movie": "The Matrix" }' \
  http://localhost/parse/functions/averageStars
```
This is my terminal `output`:
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /parse/functions/averageStars</pre>
</body>
</html>
```
I think we need to have cloud code usage in this repository ReadMe file and it's not related to StackOverflow. It seems other likes me have same issue: https://github.com/bitnami/bitnami-docker-parse/issues/41

**Comment by mnlbox** [comment] 2018-07-30 07:11
@andresbono I also try this `curl`:
```
curl -X POST \
  -H "X-Parse-Application-Id: myappID" \
  -H "X-Parse-REST-API-Key: 123" \
  -H "Content-Type: application/json" \
  -d '{ "movie": "The Matrix" }' \
  http://localhost:1337/parse/functions/averageStars
```

And It's also return this error in terminal:
```
{"code":141,"error":"Invalid function: \"averageStars\""}
```

**Comment by andresbono** [comment] 2018-07-30 10:42
Hi again @mnlbox, we will investigate if the problem is related to the container itself and we will update this issue.

**Comment by mnlbox** [comment] 2018-08-01 04:40
@andresbono any news about this? I also check again and it seems something is missing. :thinking:

**Comment by andresbono** [comment] 2018-08-01 10:29
Hi @mnlbox, we have tried a simple example to test the _CloudCode_ functionality in our container. These are the steps that we have followed:

1. In the parse container, execute:
  `mkdir -p /opt/bitnami/parse/cloud`.

2. Create a simple CloudCode script (`/opt/bitnami/parse/cloud/main.js`) with the following content:
```
Parse.Cloud.define("sayHi", function(request, response) {
    response.success("Hi there!");
});
```

3. Reference the script in the parse config file (`/opt/bitnami/parse/config.json`). I think this is the step that you are missing 🤔
```diff
 {
   ...
   "port": "1337",
   "host": "0.0.0.0",
+  "cloud": "./cloud/main.js",
   "serverURL": "http://127.0.0.1:1337/parse",
   ...
 }
```

4. Restart Parse:
```
nami restart parse
```

5. Access Parse Dashboard API Console http://localhost/apps/MyDashboard/api_console and do the query:

![image](https://user-images.githubusercontent.com/1057973/43516547-273eb476-9586-11e8-96f2-41fbff105425.png)


Hope this helps,
-Andrés B.

**Comment by andresbono** [comment] 2018-08-02 08:38
@mnlbox, we are going to close this issue and continue the conversations in bitnami/bitnami-docker-parse#41 as this is more related to _parse_ itself than _parse-dashboard_. Thanks!

**Closed by andresbono** 2018-08-02 08:38 UTC
